spring.datasource.url=jdbc:postgresql://localhost:5432/car_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JMS / Artemis
spring.artemis.mode=native
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

# Логические имена очередей
app.jms.admin-queue=admin.notifications
app.jms.orders-queue=orders.queue

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public